services:
    career_day_dev:
        container_name: 'career_day_dev'
        ports:
            - '5438:5432'
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
        image: postgres:14.15-alpine3.21
        volumes:
            - pg_data:/var/lib/postgresql/data
        restart: always

volumes:
    pg_data:
